/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestaocomercial.view;

import gestaocomercial.GestaoComercial;
import gestaocomercial.controller.ControleClientes;
import gestaocomercial.controller.ControleProdutos;
import gestaocomercial.controller.ControleVendas;
import gestaocomercial.model.Cliente;
import gestaocomercial.model.Endereco;
import gestaocomercial.model.Par;
import gestaocomercial.model.Produto;
import gestaocomercial.model.StatusVenda;
import gestaocomercial.model.TipoProduto;
import gestaocomercial.model.Venda;
import java.awt.Component;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Martins
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private final ControleClientes controleClientes = new ControleClientes();
    private final ControleProdutos controleProdutos = new ControleProdutos();
    private final ControleVendas controleVendas = new ControleVendas();
    
    /**
     * Creates new form menuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        GestaoComercial.insercaoTeste1(controleClientes, controleProdutos, controleVendas);
        tabelaCadVendaProdutos.removeColumn(tabelaCadVendaProdutos.getColumnModel().getColumn(8));
    }

    private Cliente getDadosCliente(){
        String nome = txtCadClienteNome.getText();
        String cpf = txtCadClienteCPF.getText();
        int codigo = (Integer) spinCadClienteCodigo.getValue();
        String email = txtCadClienteEmail.getText();
        String senha = String.copyValueOf(txtCadClienteSenha.getPassword());
        String txt_enderecos = txtCadClienteEnderecos.getText();
        double saldo = Double.parseDouble(txtCadClienteSaldo.getText().replaceAll(",", "."));
        StringTokenizer st = new StringTokenizer(txt_enderecos, "\n");
        StringTokenizer st2;
        ArrayList<Endereco> enderecos = new ArrayList<>();
        String estado, cidade, rua, complemento;
        int numero;
        while(st.hasMoreTokens()){
            st2 = new StringTokenizer(st.nextToken(), "@");
            
            while(st2.hasMoreTokens()){
                estado = st2.nextToken();
                cidade = st2.nextToken();
                rua = st2.nextToken();
                numero = Integer.parseInt(st2.nextToken());
                complemento = st2.nextToken();
                enderecos.add(new Endereco(estado, cidade, rua, numero, complemento));
            }
        }
        Cliente cliente = new Cliente(codigo, cpf, nome, email, senha, enderecos, saldo);
        return cliente;
    }
    
    private Produto getDadosProduto(){
        return new Produto(
                (Integer) spinProdutoCodigo.getValue(),
                txtProdutoDescricao.getText(),
                (Integer) spinProdutoEstoque.getValue(),
                txtProdutoCategoria.getText(),
                (TipoProduto) comboProdutoTipo.getSelectedItem(),
                txtProdutoParticularidade.getText(),
                Double.parseDouble(txtProdutoPreco.getText())
        );
    }
    
    private Venda getDadosVenda(){
        ArrayList<Par<Produto, Integer>> produtos_vendidos = new ArrayList<>();
        int i, qtd_linhas = tabelaCadVendaProdutos.getRowCount();
        DefaultTableModel defaultTableModel = (DefaultTableModel) tabelaCadVendaProdutos.getModel();
        for(i = 0; i < qtd_linhas; i++){
            produtos_vendidos.add(new Par<>((Produto) defaultTableModel.getValueAt(i, 8), (Integer) defaultTableModel.getValueAt(i, 1)));
        }
        
        if(produtos_vendidos.isEmpty()) // nenhum produto foi comprado...
            return null;
        
        return new Venda(
                (Integer) spinVendaCodVenda.getValue(),
                (Cliente) comboVendaCliente.getSelectedItem(),
                (Endereco) comboVendaEndereco.getSelectedItem(),
                new Date(),
                (StatusVenda) comboCadVendaStatus.getSelectedItem(),
                produtos_vendidos
        );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane12 = new javax.swing.JTabbedPane();
        jTabbedPane13 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnProdutoListarComFiltro = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtListProdutoNome = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtProdutoListarComFiltro = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnProdutoListarSemFiltro = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtProdutoListarSemFiltro = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnProdutoCadastrar = new javax.swing.JButton();
        txtProdutoDescricao = new javax.swing.JTextField();
        txtProdutoCategoria = new javax.swing.JTextField();
        spinProdutoCodigo = new javax.swing.JSpinner();
        spinProdutoEstoque = new javax.swing.JSpinner();
        txtProdutoPreco = new javax.swing.JFormattedTextField();
        comboProdutoTipo = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtProdutoParticularidade = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        btnVendaStatus = new javax.swing.JButton();
        comboVendaStatus = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        spinStatusVendaCodigo = new javax.swing.JSpinner();
        jPanel10 = new javax.swing.JPanel();
        btnListVenda = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtListVendaDataInicio = new javax.swing.JFormattedTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtListVenda = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtListVendaDataTermino = new javax.swing.JFormattedTextField();
        jPanel11 = new javax.swing.JPanel();
        btnCadVenda = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        spinVendaCodVenda = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        comboVendaCliente = new javax.swing.JComboBox<>();
        comboVendaEndereco = new javax.swing.JComboBox<>();
        comboVendaProduto = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabelaCadVendaProdutos = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboCadVendaStatus = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        txtCadVendaPreco = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinCadVendaQtdProdutoComprada = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane17 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        txtListClienteNome = new javax.swing.JTextField();
        btnListCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtListaClientesComFiltro = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtListaClientesSemFiltro = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        btntCadCliente = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCadClienteEmail = new javax.swing.JTextField();
        txtCadClienteNome = new javax.swing.JTextField();
        txtCadClienteCPF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCadClienteEnderecos = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spinCadClienteCodigo = new javax.swing.JSpinner();
        txtCadClienteSenha = new javax.swing.JPasswordField();
        txtCadClienteSaldo = new javax.swing.JFormattedTextField();
        btntAlterarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(153, 204, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jTabbedPane12.setBackground(new java.awt.Color(153, 255, 255));

        jTabbedPane13.setBackground(new java.awt.Color(153, 153, 255));

        btnProdutoListarComFiltro.setText("Listar");
        btnProdutoListarComFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoListarComFiltroActionPerformed(evt);
            }
        });

        jLabel22.setText("Nome do produto:");

        txtProdutoListarComFiltro.setColumns(20);
        txtProdutoListarComFiltro.setRows(5);
        jScrollPane6.setViewportView(txtProdutoListarComFiltro);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtListProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdutoListarComFiltro)
                .addContainerGap(423, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtListProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProdutoListarComFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );

        jTabbedPane13.addTab("Listar por nome do produto", jPanel2);

        btnProdutoListarSemFiltro.setText("Listar");
        btnProdutoListarSemFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoListarSemFiltroActionPerformed(evt);
            }
        });

        txtProdutoListarSemFiltro.setColumns(20);
        txtProdutoListarSemFiltro.setRows(5);
        jScrollPane5.setViewportView(txtProdutoListarSemFiltro);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnProdutoListarSemFiltro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProdutoListarSemFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );

        jTabbedPane13.addTab("Listar todos os produtos", jPanel3);

        jTabbedPane12.addTab("Listar Produtos", jTabbedPane13);

        jLabel23.setText("Código:");

        jLabel24.setText("Descrição:");

        jLabel25.setText("Quantidade em Estoque:");

        jLabel26.setText("Categoria:");

        jLabel28.setText("Tipo de Produto: ");

        jLabel29.setText("Particularidade: ");

        jLabel30.setText("Preço:");

        btnProdutoCadastrar.setBackground(new java.awt.Color(153, 255, 153));
        btnProdutoCadastrar.setText("Cadastrar");
        btnProdutoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoCadastrarActionPerformed(evt);
            }
        });

        txtProdutoDescricao.setText("Jogos Vorazes");

        txtProdutoCategoria.setText("Geral");

        spinProdutoCodigo.setModel(new javax.swing.SpinnerNumberModel(3, 1, null, 1));

        spinProdutoEstoque.setModel(new javax.swing.SpinnerNumberModel(75, 1, null, 1));

        txtProdutoPreco.setText("25.99");

        comboProdutoTipo.setModel(new javax.swing.DefaultComboBoxModel(TipoProduto.values()));

        txtProdutoParticularidade.setColumns(20);
        txtProdutoParticularidade.setLineWrap(true);
        txtProdutoParticularidade.setRows(5);
        txtProdutoParticularidade.setText("Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games: a televised competition in which two teenagers from each of the twelve Districts of Panem are chosen at random to fight to the death. ");
        jScrollPane4.setViewportView(txtProdutoParticularidade);

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinProdutoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProdutoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProdutoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboProdutoTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spinProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProdutoCadastrar)))
                .addGap(38, 38, 38))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnProdutoCadastrar, jButton2});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(spinProdutoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(txtProdutoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(spinProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtProdutoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(comboProdutoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdutoCadastrar)
                    .addComponent(jButton2))
                .addGap(23, 23, 23))
        );

        jTabbedPane12.addTab("Cadastrar Produto", jPanel8);

        jTabbedPane1.addTab("Produto", jTabbedPane12);

        jTabbedPane4.setBackground(new java.awt.Color(153, 255, 255));
        jTabbedPane4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane4StateChanged(evt);
            }
        });
        jTabbedPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane4MouseClicked(evt);
            }
        });

        btnVendaStatus.setText("Alterar Status");
        btnVendaStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaStatusActionPerformed(evt);
            }
        });

        comboVendaStatus.setModel(new javax.swing.DefaultComboBoxModel(StatusVenda.values()));

        jLabel19.setText("Código da Venda:");

        jLabel20.setText("Status:");

        spinStatusVendaCodigo.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboVendaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinStatusVendaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(btnVendaStatus)))
                .addContainerGap(330, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboVendaStatus, spinStatusVendaCodigo});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(spinStatusVendaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(comboVendaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                .addComponent(btnVendaStatus)
                .addGap(70, 70, 70))
        );

        jTabbedPane4.addTab("Status de Venda", jPanel9);

        btnListVenda.setText("Listar");
        btnListVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListVendaActionPerformed(evt);
            }
        });

        jLabel21.setText("Data ínicio:");

        txtListVendaDataInicio.setText("01/10/2019");

        txtListVenda.setColumns(20);
        txtListVenda.setRows(5);
        jScrollPane7.setViewportView(txtListVenda);

        jLabel2.setText("Data término:");

        txtListVendaDataTermino.setText("05/10/2019");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtListVendaDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtListVendaDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListVenda)
                        .addGap(0, 292, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtListVendaDataInicio, txtListVendaDataTermino});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(btnListVenda)
                    .addComponent(txtListVendaDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtListVendaDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Listar Venda por Data", jPanel10);

        btnCadVenda.setText("Cadastrar Venda");
        btnCadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadVendaActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações da Venda", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        spinVendaCodVenda.setModel(new javax.swing.SpinnerNumberModel(2, 1, null, 1));

        jLabel16.setText("Produto:");

        comboVendaCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboVendaClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        comboVendaProduto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboVendaProdutoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tabelaCadVendaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Qtd comprada", "Descrição", "Categoria", "Tipo", "Preço", "Estoque", "Particularidade", "Produto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tabelaCadVendaProdutos);

        jLabel32.setText("Cliente: ");

        jLabel3.setText("Quantidade:");

        comboCadVendaStatus.setModel(new javax.swing.DefaultComboBoxModel(StatusVenda.values()));

        jButton4.setText("Remover");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtCadVendaPreco.setEditable(false);
        txtCadVendaPreco.setText("R$0,00");

        jLabel17.setText("Preço total:");

        jLabel13.setText("Endereço:");

        jLabel4.setText("Status:");

        spinCadVendaQtdProdutoComprada.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spinCadVendaQtdProdutoComprada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinCadVendaQtdProdutoCompradaStateChanged(evt);
            }
        });

        jLabel31.setText("Código da Venda: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboVendaCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(comboVendaProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinCadVendaQtdProdutoComprada, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(comboVendaEndereco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(spinVendaCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboCadVendaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadVendaPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(spinVendaCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(comboVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(comboVendaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(comboVendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel3)
                    .addComponent(spinCadVendaQtdProdutoComprada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCadVendaPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboCadVendaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadVenda)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadVenda)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Cadastrar Venda", jPanel11);

        jTabbedPane1.addTab("Venda", jTabbedPane4);

        jTabbedPane3.setBackground(new java.awt.Color(153, 255, 255));

        jTabbedPane17.setBackground(new java.awt.Color(153, 153, 255));

        txtListClienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtListClienteNomeActionPerformed(evt);
            }
        });

        btnListCliente.setText("Listar");
        btnListCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        txtListaClientesComFiltro.setColumns(20);
        txtListaClientesComFiltro.setRows(5);
        jScrollPane3.setViewportView(txtListaClientesComFiltro);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtListClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListCliente)
                        .addGap(0, 548, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtListClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListCliente)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );

        jTabbedPane17.addTab("Listar por nome", jPanel4);

        jButton1.setText("Listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtListaClientesSemFiltro.setColumns(20);
        txtListaClientesSemFiltro.setRows(5);
        jScrollPane2.setViewportView(txtListaClientesSemFiltro);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );

        jTabbedPane17.addTab("Listar todos os Clientes", jPanel5);

        jTabbedPane3.addTab("Listar Clientes", jTabbedPane17);

        btntCadCliente.setBackground(new java.awt.Color(153, 255, 153));
        btntCadCliente.setText("Cadastrar");
        btntCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntCadClienteActionPerformed(evt);
            }
        });

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel8.setText("CPF:");

        jLabel7.setText("Nome:");

        jLabel18.setText("Código:");

        jLabel9.setText("E-mail:");

        jLabel10.setText("Senha:");

        txtCadClienteEmail.setText("silvio@santos.com");

        txtCadClienteNome.setText("Silvio Santos");

        txtCadClienteCPF.setText("123.456.789-26");

        jLabel11.setText("Endereços: (Formato: ESTADO@CIDADE@RUA@NUMERO@COMPLEMENTO) - Ex.: MG@Florestal@Rua Afonso Pereira@15@Casa");

        txtCadClienteEnderecos.setColumns(20);
        txtCadClienteEnderecos.setRows(5);
        txtCadClienteEnderecos.setText("SP@São Paulo@Rua Afonso Diniz@78@Casa\nSP@São Paulo@Rua Sebastião Donato@22@Apartamento");
        jScrollPane1.setViewportView(txtCadClienteEnderecos);

        jLabel27.setText("Atenção: Um endereço por linha com o formato acima");

        jLabel15.setText("Saldo:");

        spinCadClienteCodigo.setModel(new javax.swing.SpinnerNumberModel(3, 1, null, 1));

        txtCadClienteSenha.setText("sen123");

        txtCadClienteSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCadClienteSaldo.setText("1850.00");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)))
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel18))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCadClienteCPF)
                                    .addComponent(txtCadClienteEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtCadClienteNome)
                                    .addComponent(spinCadClienteCodigo)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCadClienteSaldo)
                                            .addComponent(txtCadClienteSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))))
                            .addComponent(jLabel11)
                            .addComponent(jLabel27)
                            .addComponent(jLabel15))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(spinCadClienteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadClienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCadClienteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCadClienteSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btntAlterarCliente.setText("Alterar");
        btntAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntAlterarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btntAlterarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntCadCliente)
                .addContainerGap())
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btntAlterarCliente, btntCadCliente});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntCadCliente)
                    .addComponent(btntAlterarCliente))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Cadastrar Cliente", jPanel7);

        jTabbedPane1.addTab("Cliente", jTabbedPane3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoCadastrarActionPerformed
    Produto produto = this.getDadosProduto();
    JOptionPane.showMessageDialog(null, controleProdutos.cadastrarProduto(produto));
    }//GEN-LAST:event_btnProdutoCadastrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    Produto produto = this.getDadosProduto();
    JOptionPane.showMessageDialog(null, controleProdutos.alterarDadosProduto(produto));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnProdutoListarSemFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoListarSemFiltroActionPerformed
    StringBuilder sb = new StringBuilder();
    ArrayList<Produto> produtos = controleProdutos.getProdutos(null);
    for(Produto produto : produtos){
        sb.append(produto.toString());
    }
    txtProdutoListarSemFiltro.setText(sb.toString());
    }//GEN-LAST:event_btnProdutoListarSemFiltroActionPerformed

    private void btnProdutoListarComFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoListarComFiltroActionPerformed
    StringBuilder sb = new StringBuilder();
    ArrayList<Produto> produtos = controleProdutos.getProdutos(txtListProdutoNome.getText());
    for(Produto produto : produtos){
        sb.append(produto.toString());
    }
    txtProdutoListarComFiltro.setText(sb.toString());
    }//GEN-LAST:event_btnProdutoListarComFiltroActionPerformed

    private void btntAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntAlterarClienteActionPerformed
        Cliente clienteAlterado = this.getDadosCliente();
        JOptionPane.showMessageDialog(null, controleClientes.alterarDadosCliente(clienteAlterado));
    }//GEN-LAST:event_btntAlterarClienteActionPerformed

    private void btntCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntCadClienteActionPerformed
        Cliente cliente = this.getDadosCliente();
        JOptionPane.showMessageDialog(null, controleClientes.cadastrarCliente(cliente));
    }//GEN-LAST:event_btntCadClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StringBuilder sb = new StringBuilder();
        ArrayList<Cliente> clientes = controleClientes.getClientes(null);
        for(Cliente cliente : clientes){
            sb.append(cliente.toString());
        }
        txtListaClientesSemFiltro.setText(sb.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnListClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListClienteActionPerformed
        StringBuilder sb = new StringBuilder();
        ArrayList<Cliente> clientes = controleClientes.getClientes(txtListClienteNome.getText());
        for(Cliente cliente : clientes){
            sb.append(cliente.toString());
        }
        txtListaClientesComFiltro.setText(sb.toString());
    }//GEN-LAST:event_btnListClienteActionPerformed

    private void txtListClienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtListClienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtListClienteNomeActionPerformed

    private void btnListVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListVendaActionPerformed
    StringBuilder sb = new StringBuilder();
    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
    Date dataInicio = null, dataTermino = null;
    try {
         dataInicio = simpleDateFormat.parse(txtListVendaDataInicio.getText());
         dataTermino = simpleDateFormat.parse(txtListVendaDataTermino.getText());
    } catch (ParseException ex) {
//        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Data em formato inválido!");
        return;
    }
    dataTermino.setTime(dataTermino.getTime() + 86400000 - 1000);
    ArrayList<Venda> vendas = controleVendas.getVendas(dataInicio, dataTermino);
    for(Venda venda : vendas){
        sb.append(venda.toString());
    }
    txtListVenda.setText(sb.toString());
    }//GEN-LAST:event_btnListVendaActionPerformed

    private void btnVendaStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaStatusActionPerformed
    if(controleVendas.alterarStatusVenda((Integer) spinStatusVendaCodigo.getValue(), (StatusVenda) comboVendaStatus.getSelectedItem())){
        JOptionPane.showMessageDialog(null, "Status da venda alterado com sucesso!");
    } else{
        JOptionPane.showMessageDialog(null, "Venda não encontrada", "Status não alterado", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnVendaStatusActionPerformed

    private void atualizarTelaCadVenda(int k){
        if(jTabbedPane4.getSelectedIndex() == 1){
            txtListVendaDataTermino.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        } else if(jTabbedPane4.getSelectedIndex() == 2){
            if(k != 1){
                comboVendaCliente.setModel(new javax.swing.DefaultComboBoxModel(controleClientes.getClientes(null).toArray()));
                comboVendaCliente.setRenderer(new ListCellRenderer<Object>() {
                    @Override
                    public Component getListCellRendererComponent(JList<? extends Object> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                        Object item = ((Cliente) value).getNome() + " - CPF: " + ((Cliente) value).getCPF() + 
                                (" - Saldo: R$" + new DecimalFormat("0.00").format(((Cliente) value).getSaldo())).replace(".", ",");
                        return new DefaultListCellRenderer().getListCellRendererComponent(list, item, index, isSelected, cellHasFocus);
                    }
                });
            }
            comboVendaEndereco.setModel(new javax.swing.DefaultComboBoxModel(((Cliente) comboVendaCliente.getSelectedItem()).getEnderecos().toArray()));
            comboVendaEndereco.setRenderer(new ListCellRenderer<Object>() {
                @Override
                public Component getListCellRendererComponent(JList<? extends Object> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                    Object item = ((Endereco) value).getEstado() + " - " + ((Endereco) value).getCidade() + " - " + 
                            ((Endereco) value).getRua() + " - " + ((Endereco) value).getComplemento();
                    return new DefaultListCellRenderer().getListCellRendererComponent(list, item, index, isSelected, cellHasFocus);
                }
            });
            comboVendaProduto.setModel(new javax.swing.DefaultComboBoxModel(controleProdutos.getProdutos(null).toArray()));
            comboVendaProduto.setRenderer(new ListCellRenderer<Object>() {
                @Override
                public Component getListCellRendererComponent(JList<? extends Object> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                    Object item = "Cod: " + ((Produto) value).getCodigo() + 
                            " - " + ((Produto) value).getDescricao() + (" - R$" + new DecimalFormat("0.00").format(((Produto) value).getPreco())).replace(".", ",") +
                            " - Estoque: " + ((Produto) value).getQtdEstoque();
                    return new DefaultListCellRenderer().getListCellRendererComponent(list, item, index, isSelected, cellHasFocus);
                }
            });
            atualizarPreco();
        }
    }
    
    private void jTabbedPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane4MouseClicked
//        atualizarTelaCadVenda(0);
    }//GEN-LAST:event_jTabbedPane4MouseClicked

    private void atualizarPreco(){
        int i, qtd_linhas = tabelaCadVendaProdutos.getRowCount();
        DefaultTableModel defaultTableModel = (DefaultTableModel) tabelaCadVendaProdutos.getModel();
        double preco, preco_total = 0;
        for(i = 0; i < qtd_linhas; i++){
            try{
//                System.out.println(((String) defaultTableModel.getValueAt(i, 5)).replace("R$", "").replace(",", "."));
                preco = Double.parseDouble(((String) defaultTableModel.getValueAt(i, 5)).replace("R$", "").replace(",", ".")) * ((Integer) defaultTableModel.getValueAt(i, 1));
            } catch(NumberFormatException ex){
                ex.printStackTrace();
                preco = 0;
            }
            preco_total += preco;
        }
        txtCadVendaPreco.setText(("R$" + new DecimalFormat("0.00").format(preco_total)).replace(".", ","));
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Produto produto = (Produto) comboVendaProduto.getSelectedItem();
        DefaultTableModel defaultTableModel = (DefaultTableModel) tabelaCadVendaProdutos.getModel();
        int i, qtd_linhas = tabelaCadVendaProdutos.getRowCount();
        for(i = 0; i < qtd_linhas; i++){
            if((Integer) defaultTableModel.getValueAt(i, 0) == produto.getCodigo()){
//                Integer nova_qtd = (Integer) defaultTableModel.getValueAt(i, 1);
//                nova_qtd += (Integer) spinCadVendaQtdProdutoComprada.getValue();
//                if(nova_qtd > (Integer) defaultTableModel.getValueAt(i, 6)){
//                    JOptionPane.showMessageDialog(null, "Só existem " + (Integer) defaultTableModel.getValueAt(i, 6) + 
//                            " unidades em estoque! Venda não atualizada...");
//                    return;
//                }
                Integer nova_qtd = (Integer) spinCadVendaQtdProdutoComprada.getValue();
                defaultTableModel.setValueAt(nova_qtd, i, 1);
                atualizarPreco();
                return;
            }
        }
        defaultTableModel.addRow(new Object[]{produto.getCodigo(), 
            (Integer) spinCadVendaQtdProdutoComprada.getValue(),
            produto.getDescricao(), 
            produto.getCategoria(),
            produto.getTipoProduto().toString(),
            ("R$" + new DecimalFormat("0.00").format(produto.getPreco())).replace(".", ","),
            produto.getQtdEstoque(),            
            produto.getParticularidade(),
            produto
        });
        atualizarPreco();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int linha_selecionada = tabelaCadVendaProdutos.getSelectedRow();
        if(linha_selecionada == -1)
            return;
        ((DefaultTableModel) tabelaCadVendaProdutos.getModel()).removeRow(linha_selecionada);
        atualizarPreco();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnCadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadVendaActionPerformed
        Venda venda = this.getDadosVenda();
        double preco_total = Double.parseDouble(txtCadVendaPreco.getText().replace("R$", "").replace(",", "."));
        if(venda.getCliente().getSaldo() < preco_total){
            JOptionPane.showMessageDialog(null, "Saldo do cliente insuficiente!");
            return;
        }        
        Par<Boolean, String> resp_venda = controleVendas.efetuarVenda(venda, controleProdutos);
        JOptionPane.showMessageDialog(null, resp_venda.second);
        if(resp_venda.first == true){
            controleClientes.atualizarSaldo(venda.getCliente().getCodigo(), venda.getCliente().getSaldo() - preco_total);
            for(int i = tabelaCadVendaProdutos.getRowCount() - 1; i >= 0; i--)
                ((DefaultTableModel) tabelaCadVendaProdutos.getModel()).removeRow(i);
            atualizarTelaCadVenda(0);
        }        
    }//GEN-LAST:event_btnCadVendaActionPerformed

    private void spinCadVendaQtdProdutoCompradaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinCadVendaQtdProdutoCompradaStateChanged
        int qtd_estoque = ((Produto) comboVendaProduto.getSelectedItem()).getQtdEstoque();
        if((Integer) spinCadVendaQtdProdutoComprada.getValue() > qtd_estoque)
            spinCadVendaQtdProdutoComprada.setValue(qtd_estoque);
    }//GEN-LAST:event_spinCadVendaQtdProdutoCompradaStateChanged

    private void comboVendaProdutoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboVendaProdutoPopupMenuWillBecomeInvisible
        spinCadVendaQtdProdutoComprada.setValue(1);
    }//GEN-LAST:event_comboVendaProdutoPopupMenuWillBecomeInvisible

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        if(jTabbedPane1.getSelectedIndex() == 1)
            atualizarTelaCadVenda(0);        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void comboVendaClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboVendaClientePopupMenuWillBecomeInvisible
        atualizarTelaCadVenda(1);        
    }//GEN-LAST:event_comboVendaClientePopupMenuWillBecomeInvisible

    private void jTabbedPane4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane4StateChanged
        atualizarTelaCadVenda(0);
    }//GEN-LAST:event_jTabbedPane4StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadVenda;
    private javax.swing.JButton btnListCliente;
    private javax.swing.JButton btnListVenda;
    private javax.swing.JButton btnProdutoCadastrar;
    private javax.swing.JButton btnProdutoListarComFiltro;
    private javax.swing.JButton btnProdutoListarSemFiltro;
    private javax.swing.JButton btnVendaStatus;
    private javax.swing.JButton btntAlterarCliente;
    private javax.swing.JButton btntCadCliente;
    private javax.swing.JComboBox<String> comboCadVendaStatus;
    private javax.swing.JComboBox<String> comboProdutoTipo;
    private javax.swing.JComboBox<String> comboVendaCliente;
    private javax.swing.JComboBox<String> comboVendaEndereco;
    private javax.swing.JComboBox<String> comboVendaProduto;
    private javax.swing.JComboBox<String> comboVendaStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane12;
    private javax.swing.JTabbedPane jTabbedPane13;
    private javax.swing.JTabbedPane jTabbedPane17;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JSpinner spinCadClienteCodigo;
    private javax.swing.JSpinner spinCadVendaQtdProdutoComprada;
    private javax.swing.JSpinner spinProdutoCodigo;
    private javax.swing.JSpinner spinProdutoEstoque;
    private javax.swing.JSpinner spinStatusVendaCodigo;
    private javax.swing.JSpinner spinVendaCodVenda;
    private javax.swing.JTable tabelaCadVendaProdutos;
    private javax.swing.JTextField txtCadClienteCPF;
    private javax.swing.JTextField txtCadClienteEmail;
    private javax.swing.JTextArea txtCadClienteEnderecos;
    private javax.swing.JTextField txtCadClienteNome;
    private javax.swing.JFormattedTextField txtCadClienteSaldo;
    private javax.swing.JPasswordField txtCadClienteSenha;
    private javax.swing.JTextField txtCadVendaPreco;
    private javax.swing.JTextField txtListClienteNome;
    private javax.swing.JTextField txtListProdutoNome;
    private javax.swing.JTextArea txtListVenda;
    private javax.swing.JFormattedTextField txtListVendaDataInicio;
    private javax.swing.JFormattedTextField txtListVendaDataTermino;
    private javax.swing.JTextArea txtListaClientesComFiltro;
    private javax.swing.JTextArea txtListaClientesSemFiltro;
    private javax.swing.JTextField txtProdutoCategoria;
    private javax.swing.JTextField txtProdutoDescricao;
    private javax.swing.JTextArea txtProdutoListarComFiltro;
    private javax.swing.JTextArea txtProdutoListarSemFiltro;
    private javax.swing.JTextArea txtProdutoParticularidade;
    private javax.swing.JFormattedTextField txtProdutoPreco;
    // End of variables declaration//GEN-END:variables
}
